server:
  port: 8085

zuul:
  routes:
    course:
      path: /course/**
      url: http://localhost:8084/course/
    user:
      path: /user/**
      url: http://localhost:8082/user/
spring:
  profiles:
    active: true