server:
  port: 8085

zuul:
  routes:
    course:
      path: /course/**
      url: http://lb.lxcyha.com:10004/course/
    user:
      path: /user/**
      url: http://lb.lxcyha.com:10003/user/
spring:
  profiles:
    active: true