server:
  name: course-dubbo-service
  port: 8086
thrift:
  user:
    ip: lb.lxcyha.com
    port: 10001
spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/course_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://${zookeeper.address}:2181
    protocol:
      name: dubbo
      port: 20880
#      host: 127.0.0.1
    scan: per.cyh.course







