server:
  name: course-dubbo-service
  port: 8083
thrift:
  user:
    ip: 127.0.0.1
    port: 7911
spring:
  datasource:
    url: jdbc:mysql://192.168.1.16:3306/couse_service?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
spirng:
  dubbo:
    server: true
    registry: N/A






