server:
  name: course-edge-service
  port: 8084


#dubbo config
spring:
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://192.168.1.16:2181
    scan: per.cyh.course





