server:
  name: course-edge-service
  port: 8084

user:
  edge:
    service:
      addr: lb.lxcyha.com:10003
#dubbo config
spring:
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://${zookeeper.address}:2181
    scan: per.cyh.course





