server:
  name: user-edge-service
  port: 8082
thrift:
  user:
    ip: user-service
    port: 7911
  message:
    ip: message-service
    port: 9090
spring:
  redis:
    port: 6379
    host: ${redis.address}
    timeout: 10000
  thymeleaf:
    cache: false
  cache:
    redis:
      time-to-live: 10000





