server:
  name: user-edge-service
  port: 8082
thrift:
  user:
    ip: lb.lxcyha.com
    port: 10001
  message:
    ip: lb.lxcyha.com
    port: 10002
spring:
  redis:
    host: ${redis.address}
    timeout: 10000
    port: 6379
  thymeleaf:
    cache: false
  cache:
    redis:
      time-to-live: 10000






